services:
  - type: web
    name: my-backend
    env: node
    plan: free
    buildCommand: npm install && npx prisma generate && npx prisma migrate deploy
    startCommand: node build/app.js
    autoDeploy: true
    envVars:
      - key: DATABASE_URL
        sync: false # از Render UI مقدار رو وارد کن
      - key: REDIS_URL
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: NODE_ENV
        value: production
